// Do not modify this file!
// It was generated by the command "yarn codegen".
// Instead update the code generation logic or the open api constracts.

export interface ExternalLabelDefinitionList {
  items: ExternalLabelDefinition[];
}

export type LabelDefinitionListScope = LabelDefinitionFilter & Cursor & Limit;

export interface LabelDefinitionExternalIdList {
  items: LabelDefinitionExternalId[];
}

export interface LabelDefinitionExternalId {
  /** The external ID provided by the client. Must be unique for the resource type. */
  externalId: CogniteExternalId;
}

/**
 * The external ID provided by the client. Must be unique for the resource type.
 * @example my.known.id
 */
export type CogniteExternalId = string;

export interface LabelDefinitionList {
  items: LabelDefinition[];

  /** The cursor to get the next page of results (if available). */
  nextCursor?: string;
}

export type LabelDefinition = ExternalLabelDefinition & {
  createdTime: EpochTimestamp;
};

/**
 * A label definition is a globally defined label that can later be attached to resources (e.g., assets). For example, can you define a "Pump" label definition and attach that label to your pump assets.
 */
export interface ExternalLabelDefinition {
  /** The external ID provided by the client. Must be unique for the resource type. */
  externalId: CogniteExternalId;

  /** Name of the label. */
  name: string;

  /** Description of the label. */
  description?: string;

  /** The id of the dataset this label belongs to. */
  dataSetId?: CogniteInternalId;
}

/**
 * The number of milliseconds since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds.
 * @format int64
 * @min 0
 */
export type EpochTimestamp = number;

/**
 * A server-generated ID for the object.
 * @format int64
 * @min 1
 * @max 9007199254740991
 */
export type CogniteInternalId = number;

export interface LabelDefinitionFilter {
  /**
   * Filter
   * Filter on labels definitions with strict matching.
   */
  filter?: {
    name?: string;
    externalIdPrefix?: ExternalIdPrefixFilter;
    dataSetIds?: DataSetIdEither[];
  };
}

/**
 * Cursor for paging through results
 */
export interface Cursor {
  /** @example 4zj0Vy2fo0NtNMb229mI9r1V3YG5NBL752kQz1cKtwo */
  cursor?: string;
}

export interface Limit {
  /**
   * Limits the number of results to return.
   * @min 1
   * @max 1000
   */
  limit?: number;
}

/**
 * filter external ids starting with the prefix specified
 */
export type ExternalIdPrefixFilter = string;

export type DataSetIdEither = DataSetInternalId | DataSetExternalId;

export interface DataSetInternalId {
  /** A server-generated ID for the object. */
  id: CogniteInternalId;
}

export interface DataSetExternalId {
  /** The external ID provided by the client. Must be unique for the resource type. */
  externalId: CogniteExternalId;
}

export interface LabelDefinitionCreateList {
  items: LabelDefinition[];
}

export type LabelDefinitionCreateResponse = LabelDefinitionCreateList;

export interface ErrorResponse {
  error: any;
}

export type LabelDefinitionListResponse = LabelDefinitionList;
