#!/usr/bin/env node
/**
 * Generates static protobuf bindings for datapoints into packages/stable.
 *
 * Env:
 *   PROTO_DIR - Absolute or relative path to v1/timeseries containing the three .proto files.
 *               Default: <repoRoot>/../protobuf-files/v1/timeseries
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const stableRoot = join(repoRoot, 'packages/stable');
const outDir = join(stableRoot, 'src/api/dataPoints/proto/generated');
const outJs = join(outDir, 'index.js');
const outDts = join(outDir, 'index.d.ts');

const pbjsPath = join(repoRoot, 'node_modules/protobufjs-cli/bin/pbjs');
const pbtsPath = join(repoRoot, 'node_modules/protobufjs-cli/bin/pbts');
if (!existsSync(pbjsPath) || !existsSync(pbtsPath)) {
  console.error(
    'protobufjs-cli not found. From the monorepo root, run: yarn install'
  );
  process.exit(1);
}

const defaultProtoDir = resolve(repoRoot, '../protobuf-files/v1/timeseries');
const protoDir = resolve(process.env.PROTO_DIR || defaultProtoDir);

const protoFiles = [
  'data_points.proto',
  'data_point_insertion_request.proto',
  'data_point_list_response.proto',
];

for (const f of protoFiles) {
  const p = join(protoDir, f);
  if (!existsSync(p)) {
    console.error(
      [
        `Missing ${p}`,
        'Clone cognitedata/protobuf-files or set PROTO_DIR to v1/timeseries.',
        'Example: PROTO_DIR=/path/to/protobuf-files/v1/timeseries yarn workspace @cognite/sdk generate:proto',
      ].join('\n')
    );
    process.exit(1);
  }
}

mkdirSync(outDir, { recursive: true });

let gitHead = '';
try {
  gitHead = execFileSync('git', ['-C', protoDir, 'rev-parse', 'HEAD'], {
    encoding: 'utf8',
  }).trim();
} catch {
  // not a git checkout or git unavailable
}

const protoDirLabel = relative(repoRoot, protoDir) || protoDir;

const pbjsArgs = [
  '-t',
  'static-module',
  '-w',
  'commonjs',
  '--no-create',
  '--no-verify',
  '--no-convert',
  '--no-delimited',
  '--force-long',
  '-o',
  outJs,
  ...protoFiles.map((f) => join(protoDir, f)),
];

execFileSync(process.execPath, [pbjsPath, ...pbjsArgs], {
  stdio: 'inherit',
  cwd: stableRoot,
});

let jsBody = readFileSync(outJs, 'utf8');
const header = [
  '/* Generated by scripts/generate-proto.mjs — do not edit.',
  ` * Proto source dir: ${protoDirLabel}`,
  ...(gitHead ? [` * Upstream revision: ${gitHead}`] : []),
  ' */\n',
].join('\n');
if (!jsBody.startsWith('/* Generated')) {
  jsBody = header + jsBody;
  writeFileSync(outJs, jsBody);
}

execFileSync(process.execPath, [pbtsPath, '-o', outDts, outJs], {
  stdio: 'inherit',
  cwd: stableRoot,
});

console.log(`Wrote ${outJs} and ${outDts}`);
