name: Auto approve PRs by dependabot

# Trigger the workflow on pull request
on: pull_request_target

jobs:
  autoapprove:
    name: Auto-Approve a PR by dependabot
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add merge label
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          add-labels: "auto-merge"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto approve
        uses: cognitedata/auto-approve-dependabot-action@v3.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
