name: Code Generation

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, synchronize, reopened]

jobs:
  stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['stable']

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 2

      - name: configure node js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run code generation for ${{ matrix.package }} package
        run: yarn codegen --package=${{ matrix.package }} generate-types && yarn lint:fix

      - name: Identify changed files
        id: changed_files
        run: echo "::set-output name=changed::$(git status --porcelain | wc -l)"

      - name: Files related to code generation was altered
        if: steps.changed_files.outputs.changed != 0
        run: echo "fix this by running 'yarn codegen --package=${{ matrix.package }} generate-types'" && exit 1
