name: Lerna permission

on:
  pull_request:
    branches:
      - master
      - 'release-*'

jobs:
  test-permission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install 🔧 # Installs dependencies
        run: yarn install --frozen-lockfile

      - name: Lerna env config
        run: |
          git config --global user.email "cognite-cicd@users.noreply.github.com"
          git config --global user.name "Cognite CICD"
          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" > /dev/null 2>&1
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_LERNA_TOKEN}} # Temporary fix to make lerna able to push the new versions commit to master
